// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihgjgpmrfqmidvwllbmn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImloZ2pncG1yZnFtaWR2d2xsYm1uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MDEzNDYsImV4cCI6MjA2OTk3NzM0Nn0.Yrf7gccAA2_IBpEG8ITt1-GUMr7dyxYbgJ2e20_0wAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});